### ISSUE TITLE
Need help using examples, "Failed to set presence: Connection has not been started"

### ISSUE THREAD

**Issue by Stef16Robbe** [jewlexx/discord-presence#117]
So I tried to run one of the examples, e.g. the [discord_presence_subscriber](https://github.com/jewlexx/discord-presence/blob/trunk/examples/discord_presence_subscriber.rs), I also tried the `discord_presence` example.

Created a Discord app at [Discord Developer Portal](https://discord.com/developers/applications), changed the ID with my own and ran the example(s), but I keep getting the error: `Failed to set presence: Connection has not been started`.

I must be missing something but I'm not sure what.

Info:
- discord-presence version: 1.2.0
- OS: Fedora 40

**Comment by jewlexx** [comment]
How do you have Discord installed (e.g. snap, flatpak, etc.)? Installs from Snap (and I think flatpak) don't work with discord presence.

**Comment by Stef16Robbe** [comment]
Ahh I figured. Yes I have it installed via Flatpak. Although rich presence via other applications like Spotify does work though.

**Comment by jewlexx** [comment]
Spotify doesn't connect to Discord's rich presence directly, but rather Discord queries Spotify for what you're listening to via the API.

Some other applications use the WebSocket API, which has since been deprecated, in favour of the IPC tunnels, which I can't connect to when Discord is run in a virtual environment.

If you can get rich presence working with the [JavaScript library](https://github.com/discordjs/RPC), or another application (not Spotify), then please let me know, and I can have a look into how they do it.
