### ISSUE TITLE
[BUG] Does not work with Ubuntu 22.04 Snap-based installs

### ISSUE THREAD

**Issue by echelon** [jewlexx/discord-presence#27]
Ubuntu 22.04's Snap-based Discord uses a different directory for configuration and IPC, resulting in the library not being able to find the IPC socket. The library will infinitely hang.

It looks like an issue for an older version of Discord was previously filed and closed. Perhaps Ubuntu changed how Snaps work. 

A debian package-based Discord works fine. 

Versions: 

- Linux 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Discord (Snap): Stable 152532 (a118a24) Host 0.0.20 Linux 64-Bit (5.15.0-48-Generic)
- rustc 1.64.0

**Comment by jewlexx** [comment]
Hey @echelon Sorry for the late response. This is an issue, more so with snap and flatpak, and the way that they sandbox apps. I will work on a solution, but as of now, it is unlikely to be fixed anytime soon. If you are aware of a solution or have one yourself please let me know

**Comment by jewlexx** [comment]
Update: I am not sure there is an easy fix for this, or even a fix at all.

Snap (and Flatpak to a lesser degree) sandbox apps in a way that makes it very hard to modify ("tamper") them, similar in terms of developer experience to how the Microsoft Store does it. Because of this, I don't think there is a way to do it with regular IPC, and as mentioned in #39, WebSockets don't seem to be usable.

For now, unfortunately, I don't think Snap is useable with Discord presence.

If you know of a working library/implementation please let me know.
